org: nihalwashere
app: jokes-api
service: jokes-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
